### ISSUE TITLE
Release 0.6.7 seems empty

### ISSUE THREAD

**Issue by felix-engelmann** [ludrao/django-tellme#53]
I've just upgrade to 0.6.7 and the package seems to be empty:
Django does not find the installed application

```
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/.../env/lib/python3.8/site-packages/django/utils/autoreload.py", line 53, in wrapper
    fn(*args, **kwargs)
  File "/home/.../env/lib/python3.8/site-packages/django/core/management/commands/runserver.py", line 110, in inner_run
    autoreload.raise_last_exception()
  File "/home/.../env/lib/python3.8/site-packages/django/utils/autoreload.py", line 76, in raise_last_exception
    raise _exception[1]
  File "/home/.../env/lib/python3.8/site-packages/django/core/management/__init__.py", line 357, in execute
    autoreload.check_errors(django.setup)()
  File "/home/.../env/lib/python3.8/site-packages/django/utils/autoreload.py", line 53, in wrapper
    fn(*args, **kwargs)
  File "/home/.../env/lib/python3.8/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/.../env/lib/python3.8/site-packages/django/apps/registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "/home/.../env/lib/python3.8/site-packages/django/apps/config.py", line 90, in create
    module = import_module(entry)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'tellme'
```

In the install process, the package is suspiciously small:

    Using cached django_tellme-0.6.7-py3-none-any.whl (6.2 kB)

compared to the old version

    Using cached django_tellme-0.6.6-py3-none-any.whl (112 kB)

and the directory `env/lib/python3.8/site-packages/tellme` disappears.

**Comment by brendanbrett** [comment]
Same issue here with 0.6.7.

**Comment by ludrao** [comment]
Yes sorry I had some packaging issue, I removes the wheel package from Pypi so you should be able to install from the src package

**Comment by felix-engelmann** [comment]
I still get an error in a freshly created virtual env and cleared cache on ubuntu 20.10

```
$ python3 -m venv env
$ source ./env/bin/activate
$ pip install django-tellme          
Collecting django-tellme
  Using cached django-tellme-0.6.7.tar.gz (101 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Building wheels for collected packages: django-tellme
  Building wheel for django-tellme (PEP 517) ... done
  Created wheel for django-tellme: filename=django_tellme-0.6.7-py3-none-any.whl size=6215 sha256=b90b186a7bcd8fba117d5e889999327e823519cd2ba28d014f8e328589303471
  Stored in directory: /home/<>/.cache/pip/wheels/dd/b8/a7/1809e875a0d3a30145098fba19da2a5d5fb7fde3dc3da2ba5c
Successfully built django-tellme
Installing collected packages: django-tellme
Successfully installed django-tellme-0.6.7
$ python
Python 3.8.6 (default, Sep 25 2020, 09:36:53) 
>>> import tellme
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'tellme'
```

**Comment by brendanbrett** [comment]
This is not working for me either. I'm trying to install via pip and the package is empty.
